spring:
  application:
    name: YancarlosHuacre

  datasource:
    url: jdbc:sqlserver://practica1.czosksomqv1p.us-east-1.rds.amazonaws.com:1433;databaseName=Practica2;encrypt=true;trustServerCertificate=true
    username: admin
    password: Yancarlos1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080
  address: 0.0.0.0
