server:
  port: ${PORT:8080}
  url: ${SERVER_URL:http://localhost:8080}

spring:
  application:
    name: YancarlosHuacre
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Practica2;encrypt=true;trustServerCertificate=true
    username: sa
    password: Yancarlos1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
